name: web
description: hi
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.0.3
  go_router: ^3.1.0
  google_fonts: ^2.3.3
  hydrated_bloc: ^8.1.0
  intl: ^0.17.0
  json_annotation: ^4.5.0
  path_provider: ^2.0.10
  url_launcher: ^6.1.2

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.1.11
  flutter_gen_runner: ^4.1.6
  flutter_test:
    sdk: flutter
  json_serializable: ^6.2.0
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.0

flutter_gen:
  output: lib/utils/gen/
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
